x-service-templates:
  payment-processor: &payment-processor
    image: zanfranceschi/payment-processor:amd64-20250707101540
    networks:
      - payment-processor
      - payment-processor-db
    deploy:
      resources:
        limits:
          cpus: "1.5"
          memory: "100MB"
  
  payment-processor-db: &payment-processor-db
    image: postgres:17-alpine
    networks:
      - payment-processor-db
    volumes:
      - ./init-processor.sql:/docker-entrypoint-initdb.d/init-processor.sql
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=rinha
    deploy:
      resources:
        limits:
          cpus: "1.5"
          memory: "250MB"

services:
  payment-processor-1:
    <<: *payment-processor
    container_name: payment-processor-default
    hostname: payment-processor-default
    environment:
      - TRANSACTION_FEE=0.05
      - RATE_LIMIT_SECONDS=5
      - INITIAL_TOKEN=123
      - DB_CONNECTION_STRING=Host=payment-processor-default-db;Port=5432;Database=rinha;Username=postgres;Password=postgres;Minimum Pool Size=15;Maximum Pool Size=20;Connection Pruning Interval=3
    ports:
      - 8001:8080
    depends_on:
      - payment-processor-db-1
    
  payment-processor-db-1:
    <<: *payment-processor-db
    container_name: payment-processor-default-db
    hostname: payment-processor-default-db

  payment-processor-2:
    <<: *payment-processor
    container_name: payment-processor-fallback
    hostname: payment-processor-fallback
    environment:
      - TRANSACTION_FEE=0.15
      - RATE_LIMIT_SECONDS=5
      - INITIAL_TOKEN=123
      - DB_CONNECTION_STRING=Host=payment-processor-fallback-db;Port=5432;Database=rinha;Username=postgres;Password=postgres;Minimum Pool Size=15;Maximum Pool Size=20;Connection Pruning Interval=3
    ports:
      - 8002:8080
    networks:
      - payment-processor
      - payment-processor-db
    depends_on:
      - payment-processor-db-2
  
  payment-processor-db-2:
    <<: *payment-processor-db
    container_name: payment-processor-fallback-db
    hostname: payment-processor-fallback-db

##### Minha infra
  api01:
    image: quarkus-payment-router-java-21:test
    container_name: api01
    depends_on:
      - api03
    hostname: api01
    ports:
      - "8081:8080"
    environment:
      PROCESS_THREAD_POOL: 20
      QUARKUS_REST_CLIENT_DEFAULT_API_URL: http://payment-processor-default:8080
      QUARKUS_REST_CLIENT_FALLBACK_API_URL: http://payment-processor-fallback:8080
      QUARKUS_REST_CLIENT_STORAGE_API_URL: http://api03:8080
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: "100MB"
    networks:
      - payment-router
      - payment-processor

  api02:
    image: quarkus-payment-router-java-21:test
    container_name: api02
    depends_on:
      - api03
    hostname: api02
    ports:
      - "8082:8080"
    environment:
      PROCESS_THREAD_POOL: 20
      QUARKUS_REST_CLIENT_DEFAULT_API_URL: http://payment-processor-default:8080
      QUARKUS_REST_CLIENT_FALLBACK_API_URL: http://payment-processor-fallback:8080
      QUARKUS_REST_CLIENT_STORAGE_API_URL: http://api03:8080
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: "100MB"
    networks:
      - payment-router
      - payment-processor

  api03:
    image: suntzu12/quarkus-payment-storage:1.0.0
    container_name: api03
    hostname: api03
    ports:
      - "8083:8080"
    environment:
      LISTEN: 8080
    deploy:
      resources:
        limits:
          cpus: "0.30"
          memory: "100MB"
    networks:
      - payment-router

  load_balancer:
    image: nginx:latest
    container_name: load_balancer
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.10"
          memory: "50MB"
    networks:
      - payment-router

networks:
  payment-processor:
    name: payment-processor
    driver: bridge
  payment-processor-db:
    driver: bridge
  payment-router:
    driver: bridge